### ISSUE TITLE
Potential bug in error handler

### ISSUE THREAD

**Issue by unusualbob** [jakswa/martaionic#2] opened 2016-02-12 23:55 UTC
Seems that `statusText` is never used after being declared, you send the `resp` object instead.
https://github.com/jakswa/martaionic/blob/master/www/js/services.js#L23

**Comment by jakswa** [comment] 2016-02-13 20:13
Thanks for this. The error states have been through a few iterations, seems I messed up the unexpected case (MARTA 500ing, it looks like). Did you see anything the caused you to hunt this down?

**Comment by jakswa** [comment] 2016-02-13 20:15
Ah looks like I got out of this one unscathed (re-building the statusText for the view, since it's the place that cares: https://github.com/jakswa/martaionic/commit/6936b5ba4197c18dc4f6aab5a23dd8ee8c428212).

I'll remove the unused variable. Thanks again!

**Comment by jakswa** [comment] 2016-02-13 20:19
Fixed in https://github.com/jakswa/martaionic/commit/89fe646f1321b1c21bb635992c5e3fcd144bd09a

**Closed as completed by jakswa** 2016-02-13 20:19 UTC

**Comment by jakswa** [comment] 2016-02-13 22:13
I cleaned up the error states that are thrown by [the node server this uses](http://github.com/jakswa/marta_api), and [while there](https://github.com/jakswa/marta_api/commit/bce1c1bb1b8519be789a2d297d85ad06ec1ae55c) I cleaned up a bug that probably prevented any error feedback from showing up.

Here are the known error states (besides connectivity) that the ionic app should show:

## 500 from the marta API proxy:

<img width="331" alt="screen shot 2016-02-13 at 4 39 55 pm" src="https://cloud.githubusercontent.com/assets/137793/13030314/6e2b4a98-d274-11e5-8677-827f5c453cda.png">

## marta API down, (and showing [its IIS error page](https://goo.gl/Z7QmH5))

<img width="335" alt="screen shot 2016-02-13 at 4 38 56 pm" src="https://cloud.githubusercontent.com/assets/137793/13030331/be42d35c-d274-11e5-86fe-c2c815e2635a.png">

## future JSON-based errors

if at some point MARTA starts spitting out error JSON, I'll be ready I hope
<img width="339" alt="screen shot 2016-02-13 at 4 38 39 pm" src="https://cloud.githubusercontent.com/assets/137793/13030334/d976d6f0-d274-11e5-9464-25c1532b4b7c.png">

**Comment by unusualbob** [comment] 2016-02-14 02:22
Hey sorry for the slow response, I've been quite busy all day. Just to ease your mind, I did not encounter this directly, just was looking through the source code and thought that section looked like a bug waiting to happen.

Cool to see all the new error screens.
